%clear;close all;clc;
if year(now)~=2021
    return
end
%% Basic
figure('Name','Image Processor','NumberTitle','off','Menubar','figure','Resize','off',......
    'Units','Normalized','Position',[0.025,0.0380,0.95,0.8824],'Color',[0.8,0.8,0.8],'ColorMap',gray(256));
screensize=get(0,'ScreenSize');
axes(gcf,'Units','Normalized','Position',[0.005,0.05,0.84,0.90],'Tag','background',...
    'XLim',[0.5,round(screensize(3)*0.95*0.84)+0.5],...
    'YLim',[0.5,round(screensize(4)*0.8824*0.90)+0.5],...
    'Box','on','Xtick',[],'Ytick',[])
image(gca,'CData',zeros(round(screensize(4)*0.8824*0.90),round(screensize(3)*0.95*0.84)));
allinfo.main_ah=axes(gcf,'Units','Normalized','Position',[0.005,0.05,0.84,0.90],'Tag','image',...
    'XLim',[0.5,1.5],'YLim',[0.5,1.5],'YDir','reverse','Box','on','Xtick',[],'Ytick',[]);axis equal
allinfo.image_ih=image(allinfo.main_ah,'CData',zeros(round(screensize(4)*0.8824*0.90),round(screensize(3)*0.95*0.84)),'ButtonDownFcn','processing_image_zoom');
%allinfo.image_lh=line(allinfo.main_ah,'XData',[],'YData',[],'Marker','.','MarkerSize',10,'Color','r');
%% Input
allinfo.filename_bh=uicontrol('Style','PushButton',...
    'Callback','processing_image_select;',...
    'String','Open','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.005 0.96 0.06 0.03]);
allinfo.path_filename_th=uicontrol('Style','Text',...
    'String','Select the image...','Fontunits','Normalized','Fontsize',0.6,...
    'BackgroundColor',[0.8,0.8,0.8],'ForegroundColor',[0.4,0.4,0.4],'HorizontalAlignment','Left',...
    'Units','Normalized','Position',[0.07 0.955 0.43 0.03]);
%% Page
allinfo.page_eh=uicontrol('Style','Edit','Tag','Page',...
    'Callback','processing_image_select',...
    'String','1','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.41,0.01,0.025,0.03]);
allinfo.page_prev_bh=uicontrol('Style','PushButton','Tag','Page',...
    'Callback','processing_image_select',...
    'String','<','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.39 0.01 0.015 0.03]);
allinfo.page_next_bh=uicontrol('Style','PushButton','Tag','Page',...
    'Callback','processing_image_select',...
    'String','>','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.44 0.01 0.015 0.03]);
%% Brightness & Constrast
allinfo.imhist_ah=axes(gcf,'Units','Normalized','Position',[0.85,0.75,0.145,0.20],'Box','on','Xtick',[],'Ytick',[]);
% forground/background
allinfo.fore_ch=uicontrol('Style','CheckBox','Value',1,'String','Foreground',...
    'Callback','processing_image_threshold',...
    'Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.85 0.96 0.07 0.03]);
allinfo.back_ch=uicontrol('Style','CheckBox','Value',1,'String','Background',...
    'Callback','processing_image_threshold',...
    'Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.925 0.96 0.07 0.03]);
% text
uicontrol('Style','Text','String','Brightness','Tag','Brightness',...
    'Fontunits','Normalized','Fontsize',0.6,'HorizontalAlignment','Left',...
    'BackgroundColor',[0.8,0.8,0.8],'Units','Normalized','Position',[0.85 0.68 0.08 0.035]);
uicontrol('Style','Text','String','Contrast','Tag','Contrast',...
    'Fontunits','Normalized','Fontsize',0.6,'HorizontalAlignment','Left',...
    'BackgroundColor',[0.8,0.8,0.8],'Units','Normalized','Position',[0.85 0.64 0.08 0.035]);
uicontrol('Style','Text','String','Light Threshold','Tag','Light_Threshold',...
    'Fontunits','Normalized','Fontsize',0.6,'HorizontalAlignment','Left',...
    'BackgroundColor',[0.8,0.8,0.8],'Units','Normalized','Position',[0.85 0.60 0.08 0.035]);
uicontrol('Style','Text','String','Dark Threshold','Tag','Dark_Threshold',...
    'Fontunits','Normalized','Fontsize',0.6,'HorizontalAlignment','Left',...
    'BackgroundColor',[0.8,0.8,0.8],'Units','Normalized','Position',[0.85 0.56 0.08 0.035]);
% Brightness
allinfo.bright_eh=uicontrol('Style','Edit','Tag','Brightness',...
    'Callback','processing_image_threshold','String','0','UserData',0,...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.95,0.685,0.025,0.03]);
uicontrol('Style','PushButton','Tag','Brightness',...
    'Callback','processing_image_threshold',...
    'String','-','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.93 0.685 0.015 0.03]);
uicontrol('Style','PushButton','Tag','Brightness',...
    'Callback','processing_image_threshold',...
    'String','+','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.98 0.685 0.015 0.03]);
% Contrast
allinfo.contrast_eh=uicontrol('Style','Edit','Tag','Contrast',...
    'Callback','processing_image_threshold','String','100','UserData',100,...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.95,0.645,0.025,0.03]);
uicontrol('Style','PushButton','Tag','Contrast',...
    'Callback','processing_image_threshold',...
    'String','-','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.93 0.645 0.015 0.03]);
uicontrol('Style','PushButton','Tag','Contrast',...
    'Callback','processing_image_threshold',...
    'String','+','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.98 0.645 0.015 0.03]);
% Light_Threshold
allinfo.light_eh=uicontrol('Style','Edit','Tag','Light_Threshold',...
    'Callback','processing_image_threshold','String','255','UserData',255,...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.95,0.605,0.025,0.03]);
uicontrol('Style','PushButton','Tag','Light_Threshold',...
    'Callback','processing_image_threshold',...
    'String','-','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.93 0.605 0.015 0.03]);
uicontrol('Style','PushButton','Tag','Light_Threshold',...
    'Callback','processing_image_threshold',...
    'String','+','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.98 0.605 0.015 0.03]);
% Dark_Threshold
allinfo.dark_eh=uicontrol('Style','Edit','Tag','Dark_Threshold',...
    'Callback','processing_image_threshold','String','10','UserData',10,...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.95,0.565,0.025,0.03]);
uicontrol('Style','PushButton','Tag','Dark_Threshold',...
    'Callback','processing_image_threshold',...
    'String','-','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.93 0.565 0.015 0.03]);
uicontrol('Style','PushButton','Tag','Dark_Threshold',...
    'Callback','processing_image_threshold',...
    'String','+','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.98 0.565 0.015 0.03]);
%% Functional Buttons
uicontrol('Style','PushButton','String','Cell Recognition Preview',...
    'Callback','processing_cell_recognize;',...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.85 0.52 0.145 0.03]);
uicontrol('Style','PushButton','String','Cell Recognition Export',...
    'Callback','processing_cell_recognize;',...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.85 0.48 0.145 0.03]);
uicontrol('Style','PushButton','String','Image Export',...
    'Callback','processing_image_export;',...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.85 0.44 0.145 0.03]);
%{
uicontrol('Style','PushButton','String','Rotate',...
    'Callback','processing_image_rotate;',...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.005 0.01 0.06 0.03]);
uicontrol('Style','PushButton','String','Trim',...
    'Callback','processing_image_trim;',...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.07 0.01 0.06 0.03]);
uicontrol('Style','PushButton','String','Batch',...
    'Callback','processing_batch_process;',...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.135 0.01 0.06 0.03]);
uicontrol('Style','PushButton','String','Scale Bar',...
    'Callback','processing_scale_bar;',...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.51 0.01 0.08 0.03]);
uicontrol('Style','PushButton','String','Alignment',...
    'Callback','processing_image_align;',...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.595 0.01 0.08 0.03]);
uicontrol('Style','PushButton','String','Exprot Image',...
    'Callback','processing_image_snapshot;',...
    'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.68 0.01 0.08 0.03]);
%}
%%
set(gcf,'Userdata',allinfo)
clear