clear;clc;
%{
已知bug
按住鼠标左键时鼠标移动过快，move点更换，delete失效
切换页面时可能出错
slice image边框外裁剪，有时会失效

tips: Click the atlas's central point to reset rotated atlas.
tips: Rotation and trimming of slice image are not must be, but very helpful.
tips: Clicking the right button will switch the mode to "Delete" temporarily during labeling.
tips: Press "b" to start drawing ROI, and press "q" to quit and segment the image.
tips: Press "s" to hide or show signal points and corresponding region names.
tips: Press "n" to make a copy of current image. 
%}
%% Basic
load([fileparts(mfilename('fullpath')),'\Atlas.mat'],'pic_region_all','color_map')
figure('Name','Slice Registrator','NumberTitle','off','Menubar','figure','Resize','on',...
    'Units','Normalized','Position',[0,0.037,1,0.88],'Color',[0.8,0.8,0.8],...
    'WindowKeypressFcn','registration_hotkey','WindowButtonUpFcn','set(gcf,"WindowButtonMotionFcn","")');
allinfo.atlas_ah=axes('NextPlot','Add','Tag','Atlas','Box','off','Units','Normalized','Position',[0.01,0.18,0.48,0.77],...
    'XLim',[0.5,1140.5],'YLim',[0.5,900.5],'Xtick',[],'Ytick',[],'YDir','reverse','UserData',pic_region_all,'Colormap',color_map);axis equal
allinfo.atlas_ih=image('Tag','Atlas','ButtonDownFcn','atlas_image_buttondown',...
    'CData',atlas_add_boundary(pic_region_all(:,:,700)));
allinfo.atlas_lh=line('XData',[],'YData',[],'Tag','Atlas','PickableParts','none',...
    'LineStyle','none','Marker','.','MarkerEdgeColor','r');% Atlas Feature Point
allinfo.atlas_rh=line('XData',[570.5,570.5],'YData',[450.5,450.5],'PickableParts','none',...
    'LineStyle','-','LineWidth',2,'Marker','.','MarkerEdgeColor','r','MarkerSize',20);% Atlas Rotation Point
allinfo.atlas_ph=line('XData',[],'YData',[],'PickableParts','none',...
    'LineStyle','none','Marker','*','MarkerEdgeColor','r');% Next Point
allinfo.slice_ah=axes('NextPlot','Add','Tag','Slice','Box','on','Units','Normalized','Position',[0.51,0.18,0.48,0.77],...
    'Xtick',[],'Ytick',[],'YDir','reverse','Colormap',gray(256));axis equal
allinfo.slice_ih=image('Tag','Slice','ButtonDownFcn','slice_image_buttondown','CData',[]);
allinfo.slice_lh=line('XData',[],'YData',[],'Tag','Slice','PickableParts','none',...
    'LineStyle','none','Marker','.','MarkerEdgeColor','r');% Slice Feature Point
allinfo.slice_sh=line('XData',[],'YData',[],'Tag','Signal','PickableParts','none',...
    'LineStyle','none','Marker','.','MarkerEdgeColor','g','MarkerSize',1);% Cell Signal
allinfo.slice_rh=line('XData',[],'YData',[],'Tag','ROI','PickableParts','none',...
    'LineStyle','-','Marker','.','MarkerEdgeColor','c');% ROI
%% Path Selection
allinfo.slice_path_bh=uicontrol('Style','PushButton','Tag','Slice',...
    'Callback','slice_path_selection',...
    'String','Open','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.01 0.96 0.045 0.03]);
allinfo.slice_path_th=uicontrol('Style','Text','Tag','Slice_info',...
    'String','','Fontunits','Normalized','Fontsize',0.7,...
    'BackgroundColor',[0.8,0.8,0.8],'ForegroundColor',[0.4,0.4,0.4],'HorizontalAlignment','Left',...
    'Units','Normalized','Position',[0.06 0.958 0.35 0.03]);
%% Browser
allinfo.atlas_page_th=uicontrol('Style','Text','Tag','Atlas',...
    'String','Atlas Page','Fontunits','Normalized','Fontsize',0.6,...
    'BackgroundColor',[0.8,0.8,0.8],'HorizontalAlignment','Right',...
    'Units','Normalized','Position',[0.155,0.138,0.05,0.03]);
allinfo.atlas_page_eh=uicontrol('Style','Edit','Tag','Atlas',...
    'String','700','UserData',700,'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.21,0.14,0.025,0.03]);
allinfo.atlas_step_th=uicontrol('Style','Text','Tag','Atlas_step',...
    'String','Multipage','Fontunits','Normalized','Fontsize',0.6,...
    'BackgroundColor',[0.8,0.8,0.8],'HorizontalAlignment','Right',...
    'Units','Normalized','Position',[0.275,0.138,0.05,0.03]);
allinfo.atlas_step_eh=uicontrol('Style','Edit','Tag','Atlas_step',...
    'String','10','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.33,0.14,0.02,0.03]);
allinfo.atlas_prev1_bh=uicontrol('Style','PushButton','Tag','Atlas',...
    'Callback','atlas_page_selection',...
    'String','<<','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.01 0.14 0.03 0.03]);
allinfo.atlas_prev2_bh=uicontrol('Style','PushButton','Tag','Atlas',...
    'Callback','atlas_page_selection',...
    'String','<','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.05 0.14 0.02 0.03]);
allinfo.atlas_next1_bh=uicontrol('Style','PushButton','Tag','Atlas',...
    'Callback','atlas_page_selection',...
    'String','>>','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.46 0.14 0.03 0.03]);
allinfo.atlas_next2_bh=uicontrol('Style','PushButton','Tag','Atlas',...
    'Callback','atlas_page_selection',...
    'String','>','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.43 0.14 0.02 0.03]);
allinfo.atlas_go_bh=uicontrol('Style','PushButton','Tag','Atlas',...
    'Callback','atlas_page_selection',...
    'String','Go','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.24 0.14 0.02 0.03]);
allinfo.slice_page_th=uicontrol('Style','Text','Tag','Slice',...
    'String','Slice Page','Fontunits','Normalized','Fontsize',0.6,...
    'BackgroundColor',[0.8,0.8,0.8],'HorizontalAlignment','Right',...
    'Units','Normalized','Position',[0.66,0.138,0.05,0.03]);
allinfo.slice_page_eh=uicontrol('Style','Edit','Tag','Slice',...
    'String','1','UserData',1,'Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.715,0.14,0.02,0.03]);
allinfo.slice_step_th=uicontrol('Style','Text','Tag','Slice_step',...
    'String','Multipage','Fontunits','Normalized','Fontsize',0.6,...
    'BackgroundColor',[0.8,0.8,0.8],'HorizontalAlignment','Right',...
    'Units','Normalized','Position',[0.775,0.138,0.05,0.03]);
allinfo.slice_step_eh=uicontrol('Style','Edit','Tag','Slice_step',...
    'String','5','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.83,0.14,0.02,0.03]);
allinfo.slice_prev1_bh=uicontrol('Style','PushButton','Tag','Slice',...
    'Callback','slice_page_selection',...
    'String','<<','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.51 0.14 0.03 0.03]);
allinfo.slice_prev2_bh=uicontrol('Style','PushButton','Tag','Slice',...
    'Callback','slice_page_selection',...
    'String','<','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.55 0.14 0.02 0.03]);
allinfo.slice_next1_bh=uicontrol('Style','PushButton','Tag','Slice',...
    'Callback','slice_page_selection',...
    'String','>>','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.96 0.14 0.03 0.03]);
allinfo.slice_next2_bh=uicontrol('Style','PushButton','Tag','Slice',...
    'Callback','slice_page_selection',...
    'String','>','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.93 0.14 0.02 0.03]);
allinfo.slice_go_bh=uicontrol('Style','PushButton','Tag','Slice',...
    'Callback','slice_page_selection',...
    'String','Go','Fontunits','Normalized','Fontsize',0.7,...
    'Units','Normalized','Position',[0.74 0.14 0.02 0.03]);
%% Atlas Functional Tools
allinfo.atlas_th=uicontrol('Style','Text','String',"Tip: Atlas's Z-resolution is 10mm/page.",...
    'Fontunits','Normalized','Fontsize',0.7,...
    'BackgroundColor',[0.8,0.8,0.8],'ForegroundColor',[0.4,0.4,0.4],'HorizontalAlignment','Left',...
    'Units','Normalized','Position',[0.01 0.11 0.35 0.02]);
allinfo.atlas_bgh=uibuttongroup('Title','Atlas Feature Point','Tag','Atlas',...
    'BackgroundColor',[0.8,0.8,0.8],'FontSize',10,...
    'Units','Normalized','Position',[0.01 0.01 0.48 0.095]);
allinfo.atlas_add_rh=uicontrol('Parent',allinfo.atlas_bgh,'Style','RadioButton',...
    'String','Add','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.095 0.6 0.15 0.4]);
allinfo.atlas_mov_rh=uicontrol('Parent',allinfo.atlas_bgh,'Style','RadioButton',...
    'String','Move','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.275 0.6 0.15 0.4]);
allinfo.atlas_del_rh=uicontrol('Parent',allinfo.atlas_bgh,'Style','RadioButton',...
    'String','Delete','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.455 0.6 0.15 0.4]);
allinfo.atlas_rot_rh=uicontrol('Parent',allinfo.atlas_bgh,'Style','RadioButton',...
    'String','Rotate','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.635 0.6 0.15 0.4]);
allinfo.atlas_ch=uicontrol('Parent',allinfo.atlas_bgh,'Style','CheckBox','Value',1,......
    'String','Symmetry','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.815 0.6 0.15 0.4]);
allinfo.atlas_offset_bh=uicontrol('Parent',allinfo.atlas_bgh,'Style','PushButton',...
    'Callback','atlas_image_adjust',...
    'String','Advanced','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.20 0.1 0.12 0.4]);
allinfo.atlas_load_bh=uicontrol('Parent',allinfo.atlas_bgh,'Style','PushButton',...
    'Callback','atlas_default_point_load',...
    'String','Load','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.44 0.1 0.12 0.4]);
allinfo.atlas_save_bh=uicontrol('Parent',allinfo.atlas_bgh,'Style','PushButton',...
    'Callback','atlas_default_point_save',...
    'String','Save','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.68 0.1 0.12 0.4]);
%% Slice Functional Tools
allinfo.slice_bgh=uibuttongroup('Title','Slice Feature Point','Tag','Slice',...
    'BackgroundColor',[0.8,0.8,0.8],'FontSize',10,...
    'Units','Normalized','Position',[0.51 0.01 0.48 0.095]);
allinfo.slice_add_rh=uicontrol('Parent',allinfo.slice_bgh,'Style','RadioButton',...
    'String','Add','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.045 0.6 0.10 0.4]);
allinfo.slice_mov_rh=uicontrol('Parent',allinfo.slice_bgh,'Style','RadioButton','Value',1,...
    'String','Move','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.175 0.6 0.10 0.4]);
allinfo.slice_del_rh=uicontrol('Parent',allinfo.slice_bgh,'Style','RadioButton',...
    'String','Delete','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.305 0.6 0.10 0.4]);
allinfo.slice_ins_rh=uicontrol('Parent',allinfo.slice_bgh,'Style','RadioButton',...
    'String','Insert','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.435 0.6 0.10 0.4]);
allinfo.slice_ch=uicontrol('Parent',allinfo.slice_bgh,'Style','CheckBox','Value',1,......
    'String','Copy','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.565 0.6 0.15 0.4]);
allinfo.slice_rot_bh=uicontrol('Parent',allinfo.slice_bgh,'Style','PushButton',...
    'Callback','slice_image_adjust',...
    'String','Rotate','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.04 0.1 0.12 0.4]);
allinfo.slice_trim_bh=uicontrol('Parent',allinfo.slice_bgh,'Style','PushButton',...
    'Callback','slice_image_adjust',...
    'String','Trim','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.20 0.1 0.12 0.4]);
allinfo.slice_load_bh=uicontrol('Parent',allinfo.slice_bgh,'Style','PushButton',...
    'Callback','slice_result_load',...
    'String','Load','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.36 0.1 0.12 0.4]);
allinfo.slice_analysis_bh=uicontrol('Parent',allinfo.slice_bgh,'Style','PushButton',...
    'Callback','slice_result_analysis',...
    'String','Analysis','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.52 0.1 0.12 0.4]);
allinfo.slice_preview_bh=uicontrol('Parent',allinfo.slice_bgh,'Style','PushButton',...
    'Callback','slice_result_preview',...
    'String','Preview','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.68 0.1 0.12 0.4]);
allinfo.slice_save_bh=uicontrol('Parent',allinfo.slice_bgh,'Style','PushButton',...
    'Callback','slice_result_save',...
    'String','Save','Fontunits','Normalized','Fontsize',0.7,'BackgroundColor',[0.8,0.8,0.8],...
    'Units','Normalized','Position',[0.84 0.1 0.12 0.4]);
%% Initialization
allinfo.slice_filepath={};
allinfo.slice_filename={};
allinfo.trimming=[0,0,0,0];
allinfo.rotation=0;
allinfo.atlas_adjust=zeros(1,2);
set(gcf,'Userdata',allinfo)
clear